### ISSUE TITLE
Support Scala and Python Spark code blocks

### ISSUE THREAD

**Issue by robvadai** [elehcimd/nb2md#1]
Got error messages:

- `Warning: unsupported paragraph type: '%pyspark...'`
- `Warning: unsupported paragraph type: '%spark`

**Comment by elehcimd** [comment]
@robvadai thank you for the feedback, will get this done by the end of the week.

**Comment by robvadai** [comment]
Fantastic! If there's anything I can help let me know

**Comment by robvadai** [comment]
I can send you an example file if you need one

**Comment by elehcimd** [comment]
yes thank you, I can include it in the tests

**Comment by elehcimd** [comment]
I pushed a new release, please update with `pip install -U nb2md` and let me know if the issue is resolved.

**Comment by robvadai** [comment]
Awesome! Works perfectly!

Now I have a problem converting a SQL block:

```
Notebook number of paragraphs: 14
Warning: unsupported paragraph type: '%sql
```

Should I open a separate ticket for that one?

**Comment by elehcimd** [comment]
should work now, can you please update and test again?

**Comment by robvadai** [comment]
Works like a charm!

And extra thank you for the swift updates!
